spring:
  freemarker:
    suffix: ".ftl"
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/MyGmail}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}

admin:
  default:
    username: ${ADMIN_DEFAULT_USERNAME:GmailAdmin}
    password: ${ADMIN_DEFAULT_PASSWORD:admin}
